"""fix missing content

Revision ID: 6dd8b9f303b5
Revises: 471c804b725e
Create Date: 2025-09-08 20:21:10.006681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd8b9f303b5'
down_revision = '471c804b725e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
